#!/usr/bin/php
<?php

if(php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;

$app = new App([
    'app_path' => [
        __DIR__ . '/command',
    ],
    'theme' => '\Unicorn',
    'debug' => false,
]);

$app->runCommand($argv);